config/routes.rb
Pfinance::Application.routes.draw do
  resources :categories

  resources :entries do
    collection do
      get 'home', as: :home
      get 'archive'
      get 'archive/:year/:month' => 'entries#month', as: :month
      get 'archive/:year/:month/entries' => 'entries#month_entries', as: :month_entries
    end
  end

  devise_for :users, :controllers => { :registrations => 'registrations' } 

  devise_for :views
  resources :users

  root :to => 'pages#home'

  get 'settings' => 'users#settings'

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :user
  belongs_to :category

  before_save :convert_currency

  default_scope { order('date DESC, id DESC') }
  scope :expenses, -> { where(entry_type: 0) }
  scope :income, -> { where(entry_type: 1) }

  validates :from_amount, numericality: { greater_than: 0 }
  validates :category, :presence => true

  def convert_currency
    require 'open-uri'

    if self.currency == user.currency 
      self.amount = self.from_amount
    else
      convert_string = self.currency + user.currency
      xml = Nokogiri::XML(open("http://query.yahooapis.com/v1/public/yql?q=select%20%2a%20from%20yahoo.finance.xchange%20where%20pair%20in%20%28%22#{convert_string}%22%29&env=store://datatables.org/alltableswithkeys"))

      rate = xml.search('//rate').at_xpath('Rate').content.to_f

      self.amount = (self.from_amount * rate).round(2)
    end
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]
  before_action :load_entry, only: :create

  load_and_authorize_resource

  # GET /entries
  # GET /entries.json
  def index
    redirect_to home_entries_path

    @entries = current_user.entries.expenses
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  def home
    @now = Time.now

    @expense_entries = current_user.entries.expenses.includes(:category).where("date >= ?", 30.days.ago)
    @income_entries = current_user.entries.income.where("date >= ?", 30.days.ago)
    @expenses_total = @expense_entries.to_a.sum &:amount
    @income_total = @income_entries.to_a.sum &:amount
    # @entries_by_category = @entries.group_by { |entry| entry.category.root }.sort_by { |category, entries| entries.to_a.sum &:amount }.reverse
    @expense_entries_by_category = @expense_entries.group_by { |entry| entry.category.root }.sort_by { |category, entries| entries.to_a.sum &:amount }.reverse
    # @entries_by_category = current_user.categories.roots
    # @entries_by_category.map do |category, entries|
      # entries.group_by { |entry| entry.category_id }
    # end

    # puts @entries_by_category

    @entry = Entry.new
    @categories = current_user.categories.recent

    @selected_currency = current_user.default_currency
  end

  def archive
    @entries_by_month = current_user.entries.group_by { |entry| entry.date.beginning_of_month }
  end

  def month
    @month = Time.new(params[:year], params[:month])

    @entries = current_user.entries.where("date >= ? AND date <= ?", @month.beginning_of_month, @month.end_of_month)
    @expense_entries = current_user.entries.expenses.where("date >= ? AND date <= ?", @month.beginning_of_month, @month.end_of_month)
    @income_entries = current_user.entries.income.where("date >= ? AND date <= ?", @month.beginning_of_month, @month.end_of_month)
    @expense_entries_by_category = @expense_entries.group_by { |entry| entry.category.root }.sort_by { |category, entries| entries.to_a.sum &:amount }.reverse
    @expenses_total = @expense_entries.to_a.sum &:amount
    @income_total = @income_entries.to_a.sum &:amount

    # calculate number of days based on whether this is the current month or not
    @days = ( @month.end_of_month == Time.now.end_of_month ) ? Time.now.day : @month.end_of_month.day

    @previous_page = archive_entries_path
  end

  def month_entries
    @month = Time.new(params[:year], params[:month])

    @entries = current_user.entries.where("date >= ? AND date <= ?", @month.beginning_of_month, @month.end_of_month)
    @entries_by_date = @entries.group_by { |entry| entry.date }

    @previous_page = month_entries_path
  end

  # GET /entries/new
  def new
    @entry = Entry.new
    @categories = current_user.categories
  end

  # GET /entries/1/edit
  def edit
    @categories = current_user.categories

    @selected_currency = @entry.currency

    @previous_page = month_entries_entries_path( @entry.date.year, @entry.date.month )
  end

  # POST /entries
  # POST /entries.json
  def create
    # @entry = Entry.new(entry_params)
    ep = entry_params

    if ( ep[:category_id] == nil && params[:new_category_name] != '' )
      new_category = current_user.categories.new(:name => params[:new_category_name])
      new_category.save

      ep[:category_id] = new_category.id

      p ep[:category_id]
    end

    @entry = current_user.entries.build(ep)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to root_path, notice: 'Entry created.' }
        format.json { render action: 'show', status: :created, location: root_path }
      else
        format.html { redirect_to root_path }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to edit_entry_path(@entry), notice: 'Entry updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # https://github.com/ryanb/cancan/issues/835
    def load_entry
      @entry = Entry.new(entry_params)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:user_id, :from_amount, :currency, :date, :category_id, :entry_type, :year, :month)
    end
end

app/helpers/entries_helper.rb
module EntriesHelper
  def all_currencies
    return [
      'GBP', 
      'EUR', 
      'USD', 
      'AUD', 
      'AFN', 
      'ALL', 
      'AMD', 
      'ANG', 
      'AOA', 
      'ARS', 
      'AUD', 
      'AWG', 
      'AZN', 
      'BAM', 
      'BBD', 
      'BDT', 
      'BGN', 
      'BHD', 
      'BIF', 
      'BMD', 
      'BND', 
      'BOB', 
      'BRL', 
      'BSD', 
      'BTN', 
      'BWP', 
      'BYR', 
      'BZD', 
      'CAD', 
      'CDF', 
      'CHF', 
      'CLP', 
      'CNY', 
      'COP', 
      'CRC', 
      'CUC', 
      'CUP', 
      'CVE', 
      'CZK', 
      'DJF', 
      'DKK', 
      'DOP', 
      'DZD', 
      'EGP', 
      'ERN', 
      'ETB', 
      'EUR', 
      'FJD', 
      'FKP', 
      'GBP', 
      'GEL', 
      'GGP', 
      'GHS', 
      'GIP', 
      'GMD', 
      'GNF', 
      'GTQ', 
      'GYD', 
      'HKD', 
      'HNL', 
      'HRK', 
      'HTG', 
      'HUF', 
      'IDR', 
      'ILS', 
      'IMP', 
      'INR', 
      'IQD', 
      'IRR', 
      'ISK', 
      'JEP', 
      'JMD', 
      'JOD', 
      'JPY', 
      'KES', 
      'KGS', 
      'KHR', 
      'KMF', 
      'KPW', 
      'KRW', 
      'KWD', 
      'KYD', 
      'KZT', 
      'LAK', 
      'LBP', 
      'LKR', 
      'LRD', 
      'LSL', 
      'LTL', 
      'LYD', 
      'MAD', 
      'MDL', 
      'MGA', 
      'MKD', 
      'MMK', 
      'MNT', 
      'MOP', 
      'MRO', 
      'MUR', 
      'MVR', 
      'MWK', 
      'MXN', 
      'MYR', 
      'MZN', 
      'NAD', 
      'NGN', 
      'NIO', 
      'NOK', 
      'NPR', 
      'NZD', 
      'OMR', 
      'PAB', 
      'PEN', 
      'PGK', 
      'PHP', 
      'PKR', 
      'PLN', 
      'PYG', 
      'QAR', 
      'RON', 
      'RSD', 
      'RUB', 
      'RWF', 
      'SAR', 
      'SBD', 
      'SCR', 
      'SDG', 
      'SEK', 
      'SGD', 
      'SHP', 
      'SLL', 
      'SOS', 
      'SPL', 
      'SRD', 
      'STD', 
      'SVC', 
      'SYP', 
      'SZL', 
      'THB', 
      'TJS', 
      'TMT', 
      'TND', 
      'TOP', 
      'TRY', 
      'TTD', 
      'TVD', 
      'TWD', 
      'TZS', 
      'UAH', 
      'UGX', 
      'USD', 
      'UYU', 
      'UZS', 
      'VEF', 
      'VND', 
      'VUV', 
      'WST', 
      'XAF', 
      'XCD', 
      'XDR', 
      'XOF', 
      'XPF', 
      'YER', 
      'ZAR', 
      'ZMW', 
      'ZWD'
    ]
  end
end

app/views/entries/_form.html.haml
= form_for @entry, :html => {:novalidate => true} do |f|
  - if @entry.errors.any?
    #error_explanation
      %h2= "#{pluralize(@entry.errors.count, "error")} prohibited this entry from being saved:"
      %ul
        - @entry.errors.full_messages.each do |msg|
          %li= msg
  
  .row.clearfix
    .field.amount
      = f.label :from_amount, 'Amount'
      = f.text_field :from_amount, :pattern => "\\d*"
    .field.currency
      = f.select :currency, all_currencies, :selected => @selected_currency
    .field.entry-type
      = f.select :entry_type, [['Expense', 0], ['Income', 1]]
  .row
    .field.category
      = f.label :category_id
      = hidden_field_tag 'new_category_name'
      = f.select :category_id, options_from_collection_for_select(@categories, 'id', :with_root, (@entry.category.id if @entry.category))
      %a#select-category{href: '#'}
        Select Category
  .row
    .field
      = f.label :date
      = f.date_field :date, :value => @entry.date ? @entry.date.strftime('%Y-%m-%d') : Time.zone.now.strftime('%Y-%m-%d') 
  .actions
    = f.submit 'Save'

app/views/entries/archive.html.haml
.content
  %h1.section-title Months Archive
  %ul#months
    - @entries_by_month.each do |month, entries|
      %li
        = link_to month_entries_path(month.strftime("%Y"), month.strftime("%m")), :class => 'clearfix' do
          %h2= month.strftime("%B %Y")
          %h3= number_format entries.select{|entry| entry.entry_type == 1 }.to_a.sum &:amount
          %h3.expenses= number_format entries.select{|entry| entry.entry_type == 0 }.to_a.sum &:amount

app/views/entries/edit.html.haml
.content
  %h1.section-title Edit entry

  = render 'form'

  = link_to 'Delete', @entry, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'big-button delete'

app/views/entries/home.html.haml
.content
  %h1.section-title New Entry 
  = render 'form'

#category-overlay
  %input#category-name.big-button{:type => 'text', :autocorrect => 'off', :autocapitalize => 'off', :placeholder => 'Search'}

  %ul#category-list 

.content
  .month-stats.clearfix
    %h1.section-title Past 30 Days
    
    .income
      .average
        %span Per Day
        %span.num= number_format(@income_total / 30)
      .total
        %span Total
        %span.num= number_format @income_total
    .expenses
      .average
        %span Per Day
        %span.num= number_format(@expenses_total / 30)
      .total
        %span Total
        %span.num= number_format @expenses_total

  #home-category-wrapper
    %ul#month-categories.month-list
      / - current_percentage = 0
      - @expense_entries_by_category.each do |category, entries|
        %li
          .clearfix.root-category
            / - width =  ( entries.to_a.sum &:amount ) / @expenses_total * 100 
            / .percentage-bar{ :style => 'margin-left: ' + ( number_to_percentage current_percentage, precision: 0 ) + '; width: ' + ( number_to_percentage width, precision: 0 ) }
            / - current_percentage += width
            .percentage-bar{ :style => 'width: ' + ( number_to_percentage ( entries.to_a.sum &:amount ) / @expenses_total * 100, precision: 0 ) }
            %h2.name= category.name
            %h3.percentage= number_to_percentage ( entries.to_a.sum &:amount ) / @expenses_total * 100, precision: 0
            %h3.total= number_format entries.to_a.sum &:amount
            %h3.day
              = number_format ( entries.to_a.sum &:amount ) / 30
              %span / day
            

          %ul
            - entries.group_by { |entry| entry.category }.sort_by { |category, entries| entries.to_a.sum &:amount }.reverse.each do |subcategory, subentries|
              %li
                .clearfix.sub-category
                  .percentage-bar{ :style => 'width: ' + ( number_to_percentage ( subentries.to_a.sum &:amount ) / @expenses_total * 100, precision: 0 ) }
                  %h2.name= subcategory.name
                  %h3.percentage= number_to_percentage ( subentries.to_a.sum &:amount ) / @expenses_total * 100, precision: 0
                  %h3.total= number_format subentries.to_a.sum &:amount
                  %h3.day
                    = number_format ( subentries.to_a.sum &:amount ) / 30
                    %span / day

app/views/entries/index.html.haml
%h1 Listing entries

%table
  %tr
    %th Amount
    %th Category
    %th Date
    %th

    - @entries.each do |entry|
      %tr
        %td= entry.amount
        %td= entry.category.name
        %td= entry.date.to_s(:human)
        %td= link_to 'Edit', edit_entry_path(entry)

%br

= link_to 'New Entry', new_entry_path

app/views/entries/month.html.haml
.content
  .month-stats.clearfix
    %h1.section-title= @month.strftime('%B %Y')

    / #money-bar
    /   .i{:style => 'width: ' + ( number_to_percentage @income_total / (@income_total + @expenses_total) * 100 ) }
    /   .e{:style => 'width: ' + ( number_to_percentage @expenses_total / (@income_total + @expenses_total) * 100 ) }
      
    .income
      .average
        %span Per Day
        %span.num= number_format(@income_total / @days)
      .total
        %span Total
        %span.num= number_format @income_total
    .expenses
      .average
        %span Per Day
        %span.num= number_format(@expenses_total / @days)
      .total
        %span Total
        %span.num= number_format @expenses_total

  %ul#month-categories.month-list
    - @expense_entries_by_category.each do |category, entries|
      %li
        .clearfix.root-category
          .percentage-bar{ :style => 'width: ' + ( number_to_percentage ( entries.to_a.sum &:amount ) / @expenses_total * 100, precision: 0 ) }
          %h2.name= category.name
          %h3.percentage= number_to_percentage ( entries.to_a.sum &:amount ) / @expenses_total * 100, precision: 0
          %h3.total= number_format entries.to_a.sum &:amount
          %h3.day
            = number_format ( entries.to_a.sum &:amount ) / @days
            %span / day
          

        %ul
          - entries.group_by { |entry| entry.category }.sort_by { |category, entries| entries.to_a.sum &:amount }.reverse.each do |subcategory, subentries|
            %li
              .clearfix.sub-category
                .percentage-bar{ :style => 'width: ' + ( number_to_percentage ( subentries.to_a.sum &:amount ) / @expenses_total * 100, precision: 0 ) }
                %h2.name= subcategory.name
                %h3.percentage= number_to_percentage ( subentries.to_a.sum &:amount ) / @expenses_total * 100, precision: 0
                %h3.total= number_format subentries.to_a.sum &:amount
                %h3.day
                  = number_format ( subentries.to_a.sum &:amount ) / @days
                  %span / day
  
  = link_to "All entries for #{@month.strftime('%B')}", month_entries_entries_path, :class => 'big-button orange'

app/views/entries/month_entries.haml
.content
  .month-stats.clearfix
    %h1.section-title
      = @month.strftime('%B %Y')
      Entries

  %ul#month-dates.month-list
    - @entries_by_date.each do |date, entries|
      %li
        .clearfix
          %h2= date.strftime("%A #{date.day.ordinalize}")
        
        %ul
          - entries.each do |entry|
            %li{:class => (entry.entry_type == 0) ? 'expense' : 'income' }
              = link_to edit_entry_path(entry), :class => 'clearfix' do
                %h2= entry.category.name
                %h3= number_format entry.amount, false
                .icon-chevron-right

app/views/entries/new.html.haml
%h1 New entry

= render 'form'

= link_to 'Back', root_path

app/views/entries/show.html.haml
%p#notice= notice

%p
  %b Category:
  = @entry.category.name
%p
  %b Amount:
  = @entry.amount
%p
  %b Date:
  = @entry.date

= link_to 'Edit', edit_entry_path(@entry)
\|
= link_to 'Delete', @entry, :method => :delete, :data => { :confirm => 'Are you sure?' }