config/routes.rb
Pfinance::Application.routes.draw do
  resources :categories

  resources :entries do
    collection do
      get 'home', as: :home
      get 'archive'
      get 'archive/:year/:month' => 'entries#month', as: :month
      get 'archive/:year/:month/entries' => 'entries#month_entries', as: :month_entries
    end
  end

  devise_for :users, :controllers => { :registrations => 'registrations' } 

  devise_for :views
  resources :users

  root :to => 'pages#home'

  get 'settings' => 'users#settings'

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => 'viewport', :content => 'width=device-width' }
    =# %meta{:name => 'apple-mobile-web-app-capable', :content => 'yes'}
    =# %meta{:name => 'apple-mobile-web-app-status-bar-style', :content => 'black'}
    %title Pfinance

    =# generated by realfavicongenerator.net
    = favicon_link_tag 'favicon.ico'
    = favicon_link_tag 'apple-touch-icon-57x57.png', rel: 'apple-touch-icon', sizes: '57x57'
    = favicon_link_tag 'apple-touch-icon-114x114.png', rel: 'apple-touch-icon', sizes: '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72.png', rel: 'apple-touch-icon', sizes: '72x72'
    = favicon_link_tag 'apple-touch-icon-144x144.png', rel: 'apple-touch-icon', sizes: '144x144'
    = favicon_link_tag 'apple-touch-icon-60x60.png', rel: 'apple-touch-icon', sizes: '60x6'
    = favicon_link_tag 'apple-touch-icon-120x120.png', rel: 'apple-touch-icon', sizes: '120x120'
    = favicon_link_tag 'apple-touch-icon-76x76.png', rel: 'apple-touch-icon', sizes: '76x76'
    = favicon_link_tag 'apple-touch-icon-152x152.png', rel: 'apple-touch-icon', sizes: '152x152'
    = favicon_link_tag 'favicon-196x196.png', rel: 'icon', sizes: '196x196', type: 'image/png'
    = favicon_link_tag 'favicon-160x160.png', rel: 'icon', sizes: '160x160', type: 'image/png'
    = favicon_link_tag 'favicon-96x96.png', rel: 'icon', sizes: '96x96', type: 'image/png'
    = favicon_link_tag 'favicon-16x16.png', rel: 'icon', sizes: '16x16', type: 'image/png'
    = favicon_link_tag 'favicon-32x32.png', rel: 'icon', sizes: '32x32', type: 'image/png'

    %meta{content: "#2ccaff", name: "msapplication-TileColor"}
    %meta{content: "/assets/mstile-144x144.png", name: "msapplication-TileImage"}
    %meta{content: "/assets/browserconfig.xml", name: "msapplication-config"}

    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = stylesheet_link_tag    "//fonts.googleapis.com/css?family=Ubuntu:400,700", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body.loading
    #spinner
    #wrapper
      - if @home_page == nil
        #top-links.clearfix
          = link_to_back @previous_page
          = nav_link '', home_entries_path, 'icon-home'
          = nav_link '', archive_entries_path, 'icon-calendar'
          = nav_link '', categories_path, 'icon-cabinet'
          =# link_to '', ''
          = nav_link '', settings_path, 'icon-cog settings'
          =# #page-loader
        - if notice
          %p.notice= notice
        - if alert
          %p.alert= alert
      #content
        = yield